name: freshchat
description: Copy of https://pub.dev/packages/freshchat that supports ios theming and older versions of android (Camera capture is disabled).
version: 0.1.7
author: "archie-sh <archibald.sheran@previondo.eu>"
homepage: https://github.com/archie-sh/freshchat

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: eu.smokify.freshchat
    pluginClass: FreshchatPlugin

